with-expecter: true
dir: "{{.InterfaceDir}}"
filename: "mock_{{.InterfaceName}}_test.go"
inpackage: true
packages:
  go.katupy.io/xpdt/env:
    interfaces:
      CommandLoader:
      CommandMethods:
      FileLoader:
      PathHandler:
      PathLoader:
