// Code generated by mockery v2.33.1. DO NOT EDIT.

package env

import mock "github.com/stretchr/testify/mock"

// MockCommandLoader is an autogenerated mock type for the CommandLoader type
type MockCommandLoader struct {
	mock.Mock
}

type MockCommandLoader_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCommandLoader) EXPECT() *MockCommandLoader_Expecter {
	return &MockCommandLoader_Expecter{mock: &_m.Mock}
}

// Load provides a mock function with given fields: cmd
func (_m *MockCommandLoader) Load(cmd *Command) error {
	ret := _m.Called(cmd)

	var r0 error
	if rf, ok := ret.Get(0).(func(*Command) error); ok {
		r0 = rf(cmd)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCommandLoader_Load_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Load'
type MockCommandLoader_Load_Call struct {
	*mock.Call
}

// Load is a helper method to define mock.On call
//   - cmd *Command
func (_e *MockCommandLoader_Expecter) Load(cmd interface{}) *MockCommandLoader_Load_Call {
	return &MockCommandLoader_Load_Call{Call: _e.mock.On("Load", cmd)}
}

func (_c *MockCommandLoader_Load_Call) Run(run func(cmd *Command)) *MockCommandLoader_Load_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*Command))
	})
	return _c
}

func (_c *MockCommandLoader_Load_Call) Return(_a0 error) *MockCommandLoader_Load_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCommandLoader_Load_Call) RunAndReturn(run func(*Command) error) *MockCommandLoader_Load_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCommandLoader creates a new instance of MockCommandLoader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCommandLoader(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCommandLoader {
	mock := &MockCommandLoader{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
